import { Point, PainPoint, Celebration } from './types';

export const PAIN_POINTS: PainPoint[] = [
  {
    id: 'inherited',
    icon: '🧬',
    label: 'I just inherited my faith',
    desc: "I grew up Christian but never chose it for myself.",
    hint: "This journey will help you own your faith intellectually — not just inherit it.",
  },
  {
    id: 'science',
    icon: '🔬',
    label: 'Science seems to contradict faith',
    desc: "Evolution, the Big Bang, and modern science feel incompatible with Christianity.",
    hint: "You'll discover how science actually points toward the very things Christianity claims.",
  },
  {
    id: 'bible',
    icon: '📖',
    label: "I can't trust the Bible",
    desc: "It feels outdated, contradictory, or just written by fallible men.",
    hint: "We'll trace a logical chain from truth itself to why the Bible is uniquely trustworthy.",
  },
  {
    id: 'jesus',
    icon: '✝️',
    label: "Jesus feels like one option among many",
    desc: "Why is Jesus special? Aren't all religions basically the same?",
    hint: "You'll see why Jesus makes a claim no other religious figure makes — and why it matters.",
  },
  {
    id: 'defense',
    icon: '🛡️',
    label: "I can't defend my faith to others",
    desc: "My friends ask hard questions and I don't know how to answer.",
    hint: "Each point gives you a clear, reasoned answer you can actually use in conversation.",
  },
];

export const POINTS: Point[] = [
  {
    n: 1,
    title: 'Truth About Reality Is Knowable',
    short: 'Truth',
    phase: 0,
    highlight: ['inherited', 'defense'],
    highlightMsg: "This is the foundation of every other point — if truth can't be known, nothing that follows matters. Start here.",
    takeaway: "If you say truth is unknowable, you've just stated a truth — which defeats itself.",
    claim: 'Truth about reality is knowable and objective — it exists independently of what anyone thinks or feels.',
    sg: "In Singapore's pragmatic culture, we often treat religion as a personal preference — like choosing between Hokkien mee and chicken rice. But Christianity makes a different kind of claim: not 'this works for me' but 'this is actually true.' Understanding that truth is knowable is the essential first step before evaluating any faith claim.",
    specialViz: null,
    geisler: [
      {
        head: 'The Self-Defeating Nature of Relativism',
        body: "When someone says 'there is no absolute truth,' they are making an absolute truth claim. The statement defeats itself. This is called a self-refuting proposition — it cannot be true because the moment it is true, it becomes false.",
      },
      {
        head: 'Agnosticism Has the Same Problem',
        body: "To say 'we cannot know anything about reality' is itself a claim about reality that you supposedly know. True agnosticism would require silence — yet the agnostic speaks. The very act of asserting unknowability claims knowledge.",
      },
      {
        head: 'Truth Is Correspondence',
        body: "The classical definition: a statement is true when it corresponds to reality. 'The chair exists' is true if the chair exists. This isn't a Western or cultural idea — it's the basis of every language, every court of law, and every science experiment.",
      },
      {
        head: "Pluralism Doesn't Escape the Problem",
        body: "Religious pluralism ('all religions are equally true') claims to be objectively true — which means it implicitly affirms that objective truth exists. You can't use the tools of objective reasoning to argue there is no objective reasoning.",
      },
    ],
    insight: "The person who says 'all truth is relative' has made an absolute statement. The person who says 'you can't know truth' has claimed to know something. Every attack on the knowability of truth defeats itself — which means truth's knowability is inescapable.",
    reflect: "Have you ever caught yourself saying 'that might be true for you, but not for me'? What would it mean if that statement were applied to itself?",
    verses: ['John 8:32', 'John 14:6', 'John 18:37–38'],
    scripture: '"What is truth?" — Pilate, John 18:38. He asked the right question while standing in front of the Answer.',
    ref: 'Geisler, Norman. I Don\'t Have Enough Faith to Be an Atheist, Ch. 3.',
  },
  {
    n: 2,
    title: 'Opposites Cannot Both Be True',
    short: 'Logic',
    phase: 0,
    highlight: ['defense', 'jesus'],
    highlightMsg: "When someone says 'all religions lead to God,' they're breaking this principle. Here's how to respond.",
    takeaway: "Jesus can't be 'a great teacher' and 'wrong about being God' at the same time.",
    claim: 'The Law of Non-Contradiction is foundational to all rational thought: A cannot be both A and non-A at the same time and in the same sense.',
    sg: "Singapore is famously multicultural, and the social norm is often 'all religions are the same.' But if Christianity says Jesus is the only way, and Islam says He is not divine, both cannot simultaneously be correct about Jesus. Harmony is a social virtue — but it doesn't suspend logic. Singaporeans who are sharp in science, finance, and law know this implicitly: contradictions cannot both be true.",
    specialViz: null,
    geisler: [
      {
        head: 'The Law of Non-Contradiction',
        body: "This is one of the three foundational laws of logic: something cannot be both true and false in the same way at the same time. If Jesus rose from the dead (Christianity), He did not merely swoon (Islam/liberal theology). These are mutually exclusive — one must be false.",
      },
      {
        head: 'All Dialogue Assumes This Law',
        body: "When someone disagrees with you, they're implicitly affirming the law of non-contradiction — because if it were false, your view and theirs could both be right. Disagreement itself is proof that we all operate on this law.",
      },
      {
        head: 'Eastern Mysticism\'s Challenge',
        body: "Some Buddhist and Hindu frameworks appear to deny this law. But even the teacher who says 'A and non-A can both be true' uses words that have specific meanings — and expects you to understand him, not his opposite. Even mystical denial of logic relies on logic.",
      },
      {
        head: 'Implications for Religious Pluralism',
        body: "If all religions are equally true, then no religion is uniquely true — which is itself a claim that some religions (exclusive ones) are wrong. Pluralism is not neutral. It too makes a truth claim that excludes others.",
      },
    ],
    insight: "Logic isn't a Western imposition — it's the operating system of all rational communication. Every argument against logic uses logic. This makes rational inquiry unavoidable and the search for truth meaningful.",
    reflect: "Think of a belief you hold alongside a contradictory one. What would it take to resolve the tension? Is it even possible for both to be true?",
    verses: ['Matthew 5:37', 'James 5:12', '2 Corinthians 1:17–18'],
    scripture: '"Let your yes be yes and your no be no." — Matthew 5:37. Jesus himself affirmed the law of non-contradiction.',
    ref: 'Geisler, Norman. I Don\'t Have Enough Faith to Be an Atheist, Ch. 4.',
  },
  {
    n: 3,
    title: 'The Theistic God Exists',
    short: 'God Exists',
    phase: 1,
    highlight: ['science', 'inherited'],
    highlightMsg: "The Big Bang and fine-tuning of the universe are your best friends here — they point directly to a Creator.",
    takeaway: 'Everything that begins to exist has a cause. The universe began. Therefore the universe has a cause beyond itself.',
    claim: 'A personal, all-powerful, all-knowing, all-good God — the God of theism — exists and is the best explanation for the universe we observe.',
    sg: "Singapore is a highly educated, scientifically literate society. The common assumption is that science has replaced God. But the most significant discoveries of the 20th century — the Big Bang, the fine-tuning of physical constants, the emergence of information in DNA — all point away from a self-creating universe and toward a transcendent, intelligent cause. Science hasn't buried theism; in many ways, it has revived it.",
    specialViz: 'surge',
    geisler: [
      {
        head: 'The Cosmological Argument (Kalam)',
        body: "Whatever begins to exist has a cause. The universe began to exist (confirmed by Big Bang cosmology and the Second Law of Thermodynamics). Therefore, the universe has a cause. That cause must be uncaused, timeless, immaterial, and enormously powerful — which matches the classical theistic description of God.",
      },
      {
        head: 'The Teleological Argument (Design)',
        body: "The fine-tuning of the universe is staggering. Physicist Roger Penrose calculated that the odds of a life-permitting universe arising by chance is 1 in 10 to the power of 10^123. When we find precise calibration in nature, we infer a calibrator. The universe's precision demands an explanation.",
      },
      {
        head: 'The Moral Argument',
        body: "Objective moral values exist ('torturing children for fun is wrong' is not merely an opinion). Objective moral values require a standard beyond human preference. That standard must be an objective, personal moral being — which theism calls God.",
      },
      {
        head: 'The Ontological Argument',
        body: "We can conceive of a maximally great being — one with all perfections. If such a being exists only in our minds and not in reality, we can conceive of a greater one that does exist. Therefore, a maximally great being must exist in reality. God is the greatest conceivable being.",
      },
    ],
    insight: "The universe came from nothing — not philosophical 'nothing' but absolute nothing: no space, time, matter, or energy. Whatever caused the universe must therefore be outside space, time, and matter. That's not a bad description of God.",
    reflect: "What would it mean for your daily life if the universe genuinely has a personal Creator who sustains it right now?",
    verses: ['Genesis 1:1', 'Psalm 19:1–4', 'Romans 1:20', 'Hebrews 11:3'],
    scripture: '"The heavens declare the glory of God; the skies proclaim the work of his hands." — Psalm 19:1',
    ref: 'Geisler, Norman & Turek, Frank. I Don\'t Have Enough Faith to Be an Atheist, Ch. 3–7.',
  },
  {
    n: 4,
    title: 'If God Exists, Miracles Are Possible',
    short: 'Miracles',
    phase: 1,
    highlight: ['science'],
    highlightMsg: "Your science objection applies here: once you grant a God who made natural laws, suspending them is not a problem.",
    takeaway: "A God powerful enough to create nature is powerful enough to act within it.",
    claim: 'If an all-powerful God exists, then miracles — acts that go beyond or against natural regularities — are logically possible and not scientifically disqualifiable.',
    sg: "Singaporeans are trained to think empirically. 'Where's the evidence?' is a healthy instinct. But there's a logical prior question: is it even possible for miracles to occur? Once we've established that a Creator God exists — one who set the laws of nature — then it is perfectly coherent for Him to act within His own creation. A programmer who wrote the code can write an exception.",
    specialViz: null,
    geisler: [
      {
        head: 'The Anti-Miracle Bias Is Not Scientific',
        body: "David Hume argued that miracles are improbable because natural laws are consistent. But this is circular — it assumes miracles don't happen because they don't normally happen. Science can tell us what usually occurs; it cannot, in principle, rule out exceptions caused by a being outside the natural order.",
      },
      {
        head: 'Natural Law Doesn\'t Prohibit Intervention',
        body: "Natural laws describe regularities in a closed system. But the system was opened at creation. A God who created the laws of physics is not bound by them. This is not anti-science; it's a philosophical point about the nature of law and the nature of God.",
      },
      {
        head: 'The Prior Probability Shifts',
        body: "If we have independent reasons to believe a theistic God exists (Point 3), then the prior probability of miracles rises dramatically. The question is no longer 'could this happen without God?' but 'given that God exists, is this the kind of thing He might do?'",
      },
      {
        head: 'Miracles Are Historically Assessable',
        body: "We can examine historical evidence for miracle claims just as we examine evidence for any past event. Miracles are not inherently unhistorical — they are unusual claims that require appropriately strong evidence, which is exactly what we'll examine in the next several points.",
      },
    ],
    insight: "The real question is never 'can miracles happen?' but 'did this specific miracle happen?' The first question is logical; the second is historical. Don't confuse them.",
    reflect: "Have you ever dismissed a miracle account before examining the evidence? What would 'appropriate evidence' for a miracle look like to you?",
    verses: ['Matthew 19:26', 'Luke 1:37', 'Job 42:2'],
    scripture: '"With man this is impossible, but with God all things are possible." — Matthew 19:26',
    ref: 'Geisler, Norman. Miracles and the Modern Mind.',
  },
  {
    n: 5,
    title: 'Miracles Can Confirm a Message from God',
    short: 'Confirmation',
    phase: 1,
    highlight: ['bible', 'defense'],
    highlightMsg: "This is how you link miracles to authority — a miracle-worker's message carries weight that a mere teacher's doesn't.",
    takeaway: "A miracle performed in support of a truth claim is God's signature on that claim.",
    claim: 'If God uses miracles to confirm the message of a prophet or messenger, then that messenger\'s teachings carry divine authority and should be accepted as true.',
    sg: "In Singapore's professional world, we distinguish between someone claiming authority and someone demonstrating it. A new CEO's mandate is credible when the board backs it. Similarly, if miracles are God's way of backing a messenger — a supernatural endorsement — then the messenger's claims should be taken seriously as coming from God Himself.",
    specialViz: '5es',
    geisler: [
      {
        head: 'The Logic of Divine Confirmation',
        body: "If God exists and can perform miracles, He can use them to confirm His messengers. When Moses performed signs before Pharaoh, or Jesus raised the dead, the implicit message was: 'This person speaks for Me.' Miracles function as God's authentication stamp.",
      },
      {
        head: 'Not All Miracle Claims Are Equal',
        body: "We must ask: Does the miracle actually confirm the message? Is it performed in conjunction with a specific truth claim? Genuine divine confirmation would involve a miracle tied to a message — not random displays of power. Jesus repeatedly linked His miracles to His identity claims.",
      },
      {
        head: 'The Epistemic Function of Miracles',
        body: "Miracles don't just demonstrate power — they communicate meaning. The resurrection of Jesus, if it occurred, was not just a biological anomaly but a declaration by God that Jesus' teachings, identity claims, and sacrifice were endorsed. This is why the resurrection is the hinge of Christianity.",
      },
      {
        head: 'Historical Precedent in the Old Testament',
        body: "Throughout the Hebrew Bible, prophets were validated by their miraculous track record and the fulfillment of their prophecies. False prophets were identifiable when their signs failed or their prophecies didn't come to pass (Deut. 18). God's authentication system was empirically testable.",
      },
    ],
    insight: "Miracles don't just prove God's power — they serve as God's endorsement of a specific message. If Jesus' resurrection happened, it means God endorsed everything Jesus taught, claimed, and died for.",
    reflect: "If you saw an undeniable miracle performed alongside a specific claim, what weight would you give the claim? What would it take to dismiss it?",
    verses: ['John 3:2', 'Acts 2:22', 'Hebrews 2:3–4'],
    scripture: '"Men of Israel, listen to this: Jesus of Nazareth was a man accredited by God to you by miracles, wonders and signs." — Acts 2:22',
    ref: 'Geisler, Norman. I Don\'t Have Enough Faith to Be an Atheist, Ch. 10.',
  },
  {
    n: 6,
    title: 'The New Testament Documents Are Reliable',
    short: 'NT Reliable',
    phase: 1,
    highlight: ['bible'],
    highlightMsg: "This point directly addresses your concern about the Bible. We're examining the NT as a historical document, not asking for faith first.",
    takeaway: 'The NT is the best-attested ancient document in existence — examined by the same methods as any other history.',
    claim: 'The New Testament documents, evaluated by standard historiographical criteria, are reliable historical records of the life, teachings, death, and resurrection of Jesus of Nazareth.',
    sg: "Singaporeans often assume the Bible has been changed over centuries, filled with contradictions, or is a late legend. These are historical questions — and history has answers. By every metric used to evaluate ancient documents (manuscript count, dating, eyewitness proximity, corroboration), the NT outperforms virtually every other ancient text that historians routinely accept.",
    specialViz: null,
    geisler: [
      {
        head: 'Bibliographic Test: Manuscripts',
        body: "The NT has over 5,800 Greek manuscripts, plus 18,000+ in other languages. Compare: Caesar's Gallic Wars has 10 manuscripts; Plato's works have 7. No classical scholar doubts Caesar or Plato. The NT manuscript tradition dwarfs every other ancient text in both quantity and proximity to the originals.",
      },
      {
        head: 'Internal Evidence: Eyewitness Testimony',
        body: "The NT was written within the lifetime of eyewitnesses. Paul's letters date to ~AD 48–65 — within 15–30 years of the events. Luke explicitly claims to have carefully investigated everything from eyewitnesses (Luke 1:1–4). The writers invited scrutiny from people who could have refuted them.",
      },
      {
        head: 'External Corroboration',
        body: "Roman historian Tacitus, Jewish historian Josephus, and others confirm key details: Jesus existed, was executed under Pontius Pilate during Tiberius' reign, and his followers claimed he rose. No serious historian today doubts the historical existence of Jesus.",
      },
      {
        head: 'Archaeological Confirmation',
        body: "Archaeology has repeatedly confirmed NT details. The Pool of Bethesda (John 5) — once thought fictional — was excavated and found exactly as described. Pontius Pilate's existence was confirmed by a stone inscription found in 1961. The NT's historical accuracy on verifiable details builds confidence in its unverifiable claims.",
      },
    ],
    insight: "We don't ask for blind faith in the Bible — we ask you to apply the same historical standards you'd use for any ancient document. By those standards, the NT is extraordinarily trustworthy.",
    reflect: "What standard of evidence would you apply to a first-century Roman text? Are you applying a higher standard to the NT?",
    verses: ['Luke 1:1–4', '2 Peter 1:16', '1 John 1:1–3', 'John 19:35'],
    scripture: '"We did not follow cleverly devised stories when we told you about the coming of our Lord Jesus Christ in power, but we were eyewitnesses of his majesty." — 2 Peter 1:16',
    ref: 'Geisler, Norman & Nix, William. A General Introduction to the Bible.',
  },
  {
    n: 7,
    title: 'Jesus Claimed to Be God',
    short: 'Jesus\' Claim',
    phase: 2,
    highlight: ['jesus', 'bible'],
    highlightMsg: "This is where Jesus becomes undeniably unique among religious founders. No other major figure made this specific claim.",
    takeaway: "Jesus didn't say 'follow my teachings.' He said 'I am the truth.' That changes everything.",
    claim: 'According to the reliable New Testament documents, Jesus of Nazareth explicitly and implicitly claimed to be God — divine, pre-existent, and deserving of the worship owed only to God.',
    sg: "In Singapore's multireligious landscape, Jesus is often respectfully placed alongside Buddha, Muhammad, and Confucius as a wise teacher. But this misses something explosive: none of the others claimed to be God. Buddha said he found the path. Muhammad said he delivered the message. Confucius taught ethics. Only Jesus said 'Before Abraham was, I AM' — directly invoking God's personal name.",
    specialViz: null,
    geisler: [
      {
        head: 'The "I AM" Statements',
        body: "In John 8:58, Jesus says 'Before Abraham was born, I am.' The Greek 'egō eimi' mirrors Exodus 3:14 — God's self-identification to Moses. The audience immediately tried to stone him for blasphemy. They understood exactly what he was claiming.",
      },
      {
        head: 'Accepting Worship',
        body: "In John 20:28, Thomas calls Jesus 'My Lord and my God.' Jesus accepts this without correction. Peter and Barnabas refused worship (Acts 10:25–26; 14:14–15). Angels refused worship (Rev. 22:8–9). Jesus accepted it — because He is who Thomas said He was.",
      },
      {
        head: 'The Authority Claims',
        body: "Jesus says 'You have heard it said... but I say to you' — repeatedly placing His own words on par with or above Torah. He forgave sins on His own authority (Mark 2:5–7), which Jewish leaders correctly noted only God could do. He claimed to judge all humanity (Matthew 25:31–46).",
      },
      {
        head: 'The High Priest\'s Question',
        body: "At His trial, the High Priest asked directly: 'Are you the Christ, the Son of the Blessed One?' Jesus answered, 'I am. And you will see the Son of Man sitting at the right hand of the Mighty One.' That answer got Him crucified for blasphemy — which only makes sense if it was understood as a divine claim.",
      },
    ],
    insight: "Jesus was not executed for being a good moral teacher. Nobody is executed for 'be kind to each other.' He was executed for claiming to be God. His enemies understood His claim perfectly — even if we sometimes don't.",
    reflect: "If Jesus really claimed to be God, what does that mean for how you relate to Him? Can you be neutral about someone who makes that claim?",
    verses: ['John 8:58', 'John 10:30', 'Mark 14:61–64', 'John 20:28'],
    scripture: '"I and the Father are one." — John 10:30. His audience picked up stones. They heard exactly what He meant.',
    ref: 'Geisler, Norman. The Battle for the Resurrection.',
  },
  {
    n: 8,
    title: 'Jesus\' Claim Was Miraculously Confirmed',
    short: 'Confirmed',
    phase: 2,
    highlight: ['science', 'jesus'],
    highlightMsg: "The resurrection is not a religious assertion — it's a historical claim. Here's how to think about it as evidence.",
    takeaway: 'The resurrection is the best-evidenced miracle in history, confirmed by hostile witnesses and changed lives.',
    claim: 'The miraculous resurrection of Jesus from the dead is the best historical explanation for the established facts: empty tomb, post-resurrection appearances, and the disciples\' transformation.',
    sg: "Singaporean pragmatism says: show me the evidence. The resurrection of Jesus is the most investigated miracle claim in history. Sceptical scholars, atheist historians, and hostile sources have all had to grapple with the same inconvenient facts: the tomb was empty, hundreds claimed to see Jesus alive, and a group of frightened disciples became fearless martyrs — all in Jerusalem, where authorities could have produced a body.",
    specialViz: null,
    geisler: [
      {
        head: 'The Five Established Facts',
        body: "Most historians — including sceptics — grant these: (1) Jesus died by crucifixion. (2) He was buried. (3) His tomb was found empty Sunday morning. (4) His disciples claimed to see Him alive. (5) Paul and James — former sceptics — converted after claiming to see the risen Christ.",
      },
      {
        head: 'The Hallucination Theory Fails',
        body: "Hallucinations are private, individual experiences. The NT records group appearances — 500 people at once (1 Cor. 15:6). Paul notes that most are still alive and can be questioned. Mass hallucinations of this specific type are not known to psychology. And hallucinations don't explain the empty tomb.",
      },
      {
        head: 'The Swoon Theory Fails',
        body: "Roman crucifixion was professionally lethal. The spear through Jesus' side (releasing blood and water — medical evidence of heart failure) confirms death. A swoon survivor would have limped out of a tomb, unable to convince anyone He had conquered death.",
      },
      {
        head: 'The Transformation of the Disciples',
        body: "People don't die for what they know is a lie. The disciples went from hiding behind locked doors (John 20:19) to preaching publicly in Jerusalem within 50 days, knowing crucifixion was the penalty. Something happened. The most parsimonious explanation is what they claimed: Jesus was alive.",
      },
    ],
    insight: "You don't need to start with faith to examine the resurrection. Start with the facts all historians agree on, and ask: what's the best explanation? Resurrection consistently outperforms the alternatives.",
    reflect: "If the resurrection really happened, what would it mean for your own mortality, purpose, and the decisions you're making right now?",
    verses: ['1 Corinthians 15:3–8', 'Luke 24:36–43', 'John 20:24–29', 'Acts 1:3'],
    scripture: '"He was not abandoned to the realm of the dead, nor did his body see decay. God has raised this Jesus to life, and we are all witnesses of it." — Acts 2:31–32',
    ref: 'Habermas, Gary & Licona, Michael. The Case for the Resurrection of Jesus.',
  },
  {
    n: 9,
    title: 'Therefore, Jesus Is God',
    short: 'Jesus Is God',
    phase: 2,
    highlight: ['jesus', 'defense'],
    highlightMsg: "This is the logical conclusion your conversations have been building toward — and it's not a leap of faith but a reasoned conclusion.",
    takeaway: "The evidence doesn't just suggest Jesus was a good man — it demands a verdict about His identity.",
    claim: 'Because Jesus claimed to be God (Point 7) and that claim was confirmed by His resurrection (Point 8), the logical conclusion is that Jesus is indeed God incarnate.',
    sg: "At this point the chain of reasoning — built from logic, cosmology, history, and verified documents — arrives at a conclusion that is not merely religious but rational: Jesus is God. For the Singaporean who respects clear thinking, this is not a blind leap. It's where the evidence leads. And if Jesus is God, then what He says about everything else — including the Bible — carries infinite weight.",
    specialViz: 'trilemma',
    geisler: [
      {
        head: 'The Trilemma: Liar, Lunatic, or Lord',
        body: "C.S. Lewis famously argued: Jesus claimed to be God. Either (1) He was lying — making Him a liar who let people worship Him and die for the lie; (2) He was deluded — making Him a lunatic who thought He was God; or (3) His claim was true — making Him Lord. 'Great moral teacher' is not an option when you've claimed to be God.",
      },
      {
        head: 'The Resurrection Eliminates Two Options',
        body: "The resurrection is God's verdict on Jesus. If God raised Him from the dead, God didn't endorse a liar or a lunatic — He endorsed Jesus' claims. The resurrection makes 'Lord' the only remaining option. God doesn't resurrect frauds.",
      },
      {
        head: 'The Uniqueness of the Incarnation',
        body: "The claim 'God became a man' is unique in world religion. The Greek gods were not truly human. Eastern enlightened ones were not truly God. Only Christianity claims the infinite God fully entered finite humanity — and proved it through a life, death, and resurrection accessible to historical investigation.",
      },
      {
        head: 'The Implications Are Personal',
        body: "Concluding that Jesus is God is not an endpoint — it's a beginning. If Jesus is God, then His teachings, His sacrifice, His promises, and His call to follow Him carry absolute authority. This is not just a theological conclusion. It requires a personal response.",
      },
    ],
    insight: "The question 'Who do you say I am?' (Matthew 16:15) is not a theoretical question. If Jesus is God, your answer to it is the most consequential you'll ever give.",
    reflect: "Where are you in the Trilemma? What evidence would you need to move from one position to another — and have you looked for it?",
    verses: ['Matthew 16:15–17', 'Romans 1:4', 'Colossians 2:9', 'Hebrews 1:3'],
    scripture: '"The Son is the radiance of God\'s glory and the exact representation of his being, sustaining all things by his powerful word." — Hebrews 1:3',
    ref: 'Lewis, C.S. Mere Christianity, Book 2. Geisler, Norman. Systematic Theology, Vol. 2.',
  },
  {
    n: 10,
    title: 'What Jesus Affirms Is True',
    short: 'Jesus\' Truth',
    phase: 3,
    highlight: ['bible', 'inherited'],
    highlightMsg: "This point transforms your relationship to the Bible — from inherited tradition to something much more solid.",
    takeaway: "If Jesus is God and He endorsed the Scriptures, then our confidence in them rests on His authority — not ours.",
    claim: 'If Jesus is God, then whatever He teaches or affirms is necessarily true — because God, by definition, cannot lie or be deceived.',
    sg: "In Singapore, we trust institutions based on track record and authority. If a Supreme Court judge rules on something, we take it seriously — not because we personally verified every fact, but because of the verified authority behind the ruling. If Jesus is God — demonstrated through His life, claims, and resurrection — then His endorsements of Scripture, His moral teachings, and His promises carry the highest possible authority.",
    specialViz: null,
    geisler: [
      {
        head: 'The Nature of Omniscience',
        body: "If Jesus is truly God, He possesses infinite knowledge — He cannot be mistaken. And if He is infinitely good, He cannot deceive. Whatever He affirms with authority is therefore true, not because we independently verified it but because of who He is. This is the epistemological foundation for accepting His testimony.",
      },
      {
        head: 'Jesus Affirmed the Old Testament',
        body: "Jesus repeatedly endorsed the Hebrew Scriptures as authoritative. 'Scripture cannot be broken' (John 10:35). He said 'not the smallest letter, not the least stroke of a pen, will by any means disappear from the Law' (Matthew 5:18). He treated OT accounts — Adam, Noah, Jonah — as historically real.",
      },
      {
        head: 'Jesus Authorized the New Testament',
        body: "Before His death, Jesus promised His disciples that the Holy Spirit would 'remind you of everything I have said to you' and 'guide you into all truth' (John 14:26; 16:13). This is a direct divine commissioning of the apostolic writings that became the NT.",
      },
      {
        head: 'The Coherence Test',
        body: "Jesus' endorsements are consistent — He didn't endorse Scripture selectively or revise its moral framework capriciously. His affirmations fit His character, His fulfillment of prophecy, and His ultimate authority. We have no record of Him rejecting a biblical account on the grounds that it was untrue.",
      },
    ],
    insight: "Your confidence in the Bible isn't based on church tradition or personal feeling — it's based on the testimony of God Himself, whose credentials we have examined across the last nine points.",
    reflect: "What has Jesus specifically affirmed that you've been reluctant to accept? Now that you've traced the logical chain to His authority, what changes?",
    verses: ['John 10:35', 'Matthew 5:17–18', 'John 17:17', 'John 14:26'],
    scripture: '"Sanctify them by the truth; your word is truth." — John 17:17',
    ref: 'Geisler, Norman. A General Introduction to the Bible, Ch. 1.',
  },
  {
    n: 11,
    title: 'Jesus Affirmed the Bible as God\'s Word',
    short: 'Bible Is True',
    phase: 3,
    highlight: ['bible', 'inherited'],
    highlightMsg: "This is the direct answer to your Bible questions — and it doesn't start with 'just trust it.'",
    takeaway: 'We trust the Bible not because it says so, but because Jesus — whose credentials we\'ve verified — said so.',
    claim: 'Jesus explicitly affirmed both the Old Testament and the authority of the New Testament writings, establishing the Bible as the divinely authoritative Word of God.',
    sg: "Many Singaporeans dismiss the Bible because they assume it's circular ('the Bible is true because the Bible says so'). But the reasoning here is different: we trust the Bible because Jesus — whose existence, claims, and resurrection we verified independently — endorsed it. This is not circular reasoning. It's a chain of evidence leading to a trustworthy Source who has vouched for the Scriptures.",
    specialViz: 'attributes',
    geisler: [
      {
        head: 'Jesus on the Old Testament',
        body: "Jesus quoted the OT as authoritative over 40 times. He called it 'the Word of God' (Mark 7:13), said it 'cannot be broken' (John 10:35), and treated its historical events as literally true — including the creation of Adam (Matthew 19:4–5), the flood of Noah (Matthew 24:37–38), and Jonah in the whale (Matthew 12:40).",
      },
      {
        head: 'Jesus on the New Testament',
        body: "In John 14:26, Jesus promises: 'The Holy Spirit... will teach you all things and will remind you of everything I have said to you.' In John 16:13: 'He will guide you into all truth.' These promises applied to the Apostles, whose writings became the NT. Jesus thus authorized the NT before it was written.",
      },
      {
        head: 'The Canon and Its Reliability',
        body: "The NT canon wasn't invented at Nicaea (AD 325) — it was recognized. Churches tested writings against apostolic authorship, doctrinal consistency, and universal acceptance. The Gnostic gospels failed these tests. The 27 NT books had been treated as authoritative for over two centuries before Nicaea merely confirmed what was already known.",
      },
      {
        head: 'Inspiration and Inerrancy',
        body: "2 Timothy 3:16 says Scripture is 'God-breathed.' This doesn't mean dictated robotically but that God superintended the human authors so what they wrote was what He intended. The result is a book that is authoritative in all it affirms — which is what Jesus treated it as.",
      },
    ],
    insight: "The Bible's authority doesn't rest on itself. It rests on the One who endorsed it — and whose endorsement we've spent eleven points establishing.",
    reflect: "What would it change in how you read the Bible if you treated it as Jesus treated it — as entirely trustworthy and authoritative?",
    verses: ['Mark 7:13', 'John 10:35', '2 Timothy 3:16–17', 'John 16:13'],
    scripture: '"All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness." — 2 Timothy 3:16',
    ref: 'Geisler, Norman & Nix, William. A General Introduction to the Bible.',
  },
  {
    n: 12,
    title: 'Therefore, the Bible Is the Word of God',
    short: 'Conclusion',
    phase: 3,
    highlight: ['inherited', 'bible', 'defense'],
    highlightMsg: "This is where the whole journey lands. Twelve points. One foundation. Now what?",
    takeaway: "The Bible isn't one option among many — it's the confirmed Word of the God whose existence and identity we've traced from first principles.",
    claim: 'Since God exists, Jesus is God, Jesus affirmed the Bible, and Jesus\' authority is verified, the Bible is therefore the divinely authoritative Word of God — and whatever contradicts it is false.',
    sg: "Singapore values building on solid ground. You wouldn't build an HDB flat on sand. This entire journey has been about checking the foundations — not asking you to believe because others do, but laying stone after stone from truth to logic to God's existence to miracles to history to Jesus' identity to His endorsement of Scripture. This is your foundation. It is rooted.",
    specialViz: null,
    geisler: [
      {
        head: 'The Logical Chain Is Complete',
        body: "Truth is knowable → Logic holds → God exists → Miracles are possible → Miracles confirm messengers → NT is reliable → Jesus claimed to be God → That claim was confirmed by resurrection → Jesus is God → What Jesus affirms is true → Jesus affirmed the Bible → Therefore, the Bible is the Word of God. Each link was established. The chain holds.",
      },
      {
        head: 'The Implications for Contradictions',
        body: "If the Bible is the Word of God, then claims that contradict it — no matter their source — are false. This doesn't mean we dismiss evidence; it means we investigate carefully. The Bible has repeatedly been confirmed archaeologically and historically. Where contradictions appear, they are often resolved by better scholarship.",
      },
      {
        head: 'A Living Foundation',
        body: "This isn't the end of thinking — it's the beginning of a different kind of thinking. With the Bible established as God's Word, we now have access to His self-revelation: His character, His purposes, His salvation. Christian faith is not intellectual suicide — it is intellectual and personal trust in One whose credentials have been verified.",
      },
      {
        head: 'Your Response Matters',
        body: "These twelve points are not merely academic. They converge on a Person who invites a personal response. The foundation isn't information — it's a relationship with the God who made you, entered history for you, and has spoken to you through Scripture.",
      },
    ],
    insight: "You've traced a chain of reasoning from the most basic philosophical question ('Is truth knowable?') to a specific historical Person, and from that Person to a specific Book. This is not a blind faith — it is the most well-grounded confidence available to a human being.",
    reflect: "You've gone through all twelve points. What has shifted? What still needs work? What will you do with what you've found?",
    verses: ['Psalm 119:89', 'Isaiah 40:8', 'Matthew 24:35', '1 Peter 1:23–25'],
    scripture: '"The grass withers and the flowers fall, but the word of our God endures forever." — Isaiah 40:8',
    ref: 'Geisler, Norman. I Don\'t Have Enough Faith to Be an Atheist, Ch. 13–15.',
  },
];

export const SESSION_BREAK_AFTER: number[] = [1, 5, 8];

export const CELEBRATIONS: Celebration[] = [
  {
    session: 1,
    title: "Foundation Laid",
    subtitle: "Session 1 Complete — The Case for Truth",
    established: [
      "Truth is knowable — and claims it isn't are self-defeating",
      "The Law of Non-Contradiction is inescapable",
    ],
    nextPreview: "Session 2 builds the case for God's existence — using science, cosmology, and philosophy.",
    nextSession: "Start Session 2 — Does God Exist? →",
  },
  {
    session: 2,
    title: "God Established",
    subtitle: "Session 2 Complete — God & Miracles",
    established: [
      "The theistic God is the best explanation for the universe",
      "Miracles are logically possible given God's existence",
      "Miracles can authenticate a divine messenger",
      "The New Testament documents are historically reliable",
    ],
    nextPreview: "Session 3 focuses entirely on Jesus — His claims, His confirmation, and the logical conclusion.",
    nextSession: "Start Session 3 — Who Is Jesus? →",
  },
  {
    session: 3,
    title: "Jesus Identified",
    subtitle: "Session 3 Complete — The Identity of Jesus",
    established: [
      "Jesus explicitly claimed to be God",
      "His resurrection is the best-evidenced miracle in history",
      "The logical conclusion: Jesus is God (not merely a teacher)",
    ],
    nextPreview: "Session 4 completes the chain — from Jesus' authority to the Bible's trustworthiness.",
    nextSession: "Start Session 4 — The Bible's Authority →",
  },
];
